name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build/release Electron app
        uses: github/command@v1.2.1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          command: yarn electron-builder --mac
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
